version: '3'

services:
  postgres:
    image: 'postgres:10'

  redis:
    image: redis:4.0.14

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server 
    volumes:
      - /app/node_modules # Means don't map this subdirectory in the ./server directory
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
