# Need superuser level
sudo: required
# Request to travis docker cli ready to go 
services:
  - docker 

before_install:
  - docker build -t ccazin/docker-react -f Dockerfile.dev .

script:
  - docker run ccazin/docker-react npm run test -- --version
# should be 
  #  - docker run ccazin/docker-react npm run test -- --coverage

# Deployment on AWS
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"  
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-457357339164"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

